### ISSUE TITLE
Minor coding practices issues

### ISSUE THREAD

**Issue by tkz96** [ciraganenicole/Portfolio#6]
Congratulations on completing your project! We all admire your hard work and wish you the very best.
🥳 🎈 🥳 🎉 🥳 

After a thorough review with @kosher9 and @d2ndjim, we came to the conclusion that you write really well. The few things that we would like to suggest are minor changes that will help you maintain best practices:

**1. Take some credit for your work 😄 You deserve it! 👌
2. Correct spellings make all the difference.
3. Using _classes_ and _ids_ together may not be that good of an idea. Best to use classes over ids.
4. Your design should simply start scaling after your media query kicks in. There is no need for multiple media queries unless they are a necessity.**

Other than that, fantastic job. Keep moving forward.

All the best!

**Comment by ciraganenicole** [comment]
Thanks, guys 😄
